### ISSUE TITLE
[BUG] After adding online meeting to existing meeting participants do not receive update

### ISSUE THREAD

**Issue by marcisbe** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#109] opened 2021-08-31 11:45 UTC
**HCL Product Version**
Notes 12

**Describe the bug**
After adding online meeting to existing meeting participants do not receive update.

**To Reproduce**
1. Create new Meeting and add invitees. Save and Send Invitations
2. Open just created meeting, click Schedule Online Meeting, online meeting URL is added to document
3. Press Save and Send Invitations
4. Participants calendar is not updated, they do not see online meeting URL.

**Expected behavior**
I expect that invitees calendar is updated with added online meeting link.
If for example description is edited, dialog asks if participants should be updated and as a result invitees calendar document is updated.

**Desktop (please complete the following information):**
 - OS:  Windows

**Comment by spanky762** [comment] 2021-09-01 16:06
Duplicate of issue #110 

When a user clicks the Save and Send Invitations button on a calendar entry, the code to actually send invitations (or updates to previously sent invitations) only runs if certain **_trigger_** fields have changed value.  These fields are subject, invitee(s), start date & time, end date & time, etc.  On a new calendar entry document these fields will change from blank to whatever new value is entered, so the invitations are sent.   

On an _existing_ calendar entry, things get a little strange.  If you update an existing calendar entry document, but don't change values for any of the trigger fields, then update notifications will NOT be sent, _even if you click the "Save and Send Invitations" button._  

The DOMI code does NOT update any of these trigger fields when you create, update, or delete an online meeting.  The meeting location and meeting id fields are updated, but they are not trigger fields.   

There are no plans to modify the Open Source DOMI code, as any such modification will cause DOMI to modify calendar information.  

A workaround for this can be performed as a user training issue -which is to change the Subject of the calendar document (any non-whitespace change will work) whenever an online meeting is created, updated, or deleted.  

I will refer this issue (and my response) to the Core Notes Development team so they are aware of it.

**Closed by spanky762** 2021-09-01 16:06 UTC
Labels: bug

**Comment by spanky762** [comment] 2021-09-01 17:59
I spoke with Bruce Kahn, this is fixed for 12.0.1
