### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by michaelruc** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#150] opened 2022-02-17 09:10 UTC
**HCL Product Version**
Which version of the Notes Client is in use. 
Notes Client 12.0 and 12.0.1
Mailtemplate 9.0.1

**Describe the bug**
Buttons "Find Ressources..."/"Ressource suchen..." and "Assign Colour..."/"Farbe zuweisen..." are not at 100% width, which made the look not so nice.

**To Reproduce**
Create a new Calendar entry or open an existing calendar entry

**Expected behavior**
The buttons should be good visible

**Screenshots**
![buttons](https://user-images.githubusercontent.com/99871475/154442768-1f7acb89-429c-49dd-9935-32f58f32f3ad.png)
![buttons_designer](https://user-images.githubusercontent.com/99871475/154442782-6753120b-5a99-49d6-8de8-7219a8c8cefe.png)

**Comment by paulswithers** [comment] 2022-02-17 09:16
Please clarify how this relates to the DOMI functionality. If not related, please close the issue and open through the appropriate support channels. This is not the appropriate channel for raising generic mail template issues.

**Comment by michaelruc** [comment] 2022-02-17 09:29
It appears after Domi is installed on a mailfile, on other mailfiles without domi it looks good.
For my understanding Domi installation should not change something on the calendar form itself.

We could repoduce this on german and english mailfiles.

**Comment by paulswithers** [comment] 2022-02-17 09:40
Thanks for the clarification, it's a result of running the DOMI import.

The import process exports the Calendar Entry form as DXL, adds the subform to the bottom and re-imports it, so that may be the cause.

**Comment by michaelruc** [comment] 2022-02-17 09:49
Thank you for the explanation too :).

I think it's not a big deal, as workaround we could put it to the mailtemplate and adjust it there.

**Comment by INeedCaffeine** [comment] 2022-03-09 18:10
@michaelruc : Do you see the same issue with the 12.0.1 stock mail template?

**Comment by michaelruc** [comment] 2022-03-10 07:26
@INeedCaffeine : No, don't see that issue in 12.0.1 Template (english)

**Comment by spanky762** [comment] 2022-06-28 12:46
No longer an issue with the 12.0.1 Template release.  Closing this issue.

**Closed by spanky762** 2022-06-28 12:46 UTC
Labels: bug
