### ISSUE TITLE
Adding a Room Resource isn't possible

### ISSUE THREAD

**Issue by jmcxw** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#133] opened 2021-11-26 13:24 UTC
One of our customers tried to create an online meeting with an additional room resource, which is possible to create the meeting but if the recipients try to accept the meeting they get the error "Please select an online meeting place for this online meeting". We were able to reproduce this issue as well. What I've seen while reproducing is that the Meeting Link and Password are still filled in the "location" box and the room is added to the "room" box, so both locations are set as you create the meeting.

In our opinion this is a feature which would make sense to implement as users will try to schedule meetings with other internal users and also external users where they need to reserve a room to hold the meeting.

The issue as of right now is, that you can create such a meeting with out an error on the creator side. But the recipient gets an error instead by accepting the meeting. I guess as long as such a feature is not available it would make more sense to give the creator an error, that such a meeting is not valid to create.

Let me know if I need to clarify anything further.
BR

**Comment by spanky762** [comment] 2021-12-30 13:30
I will notify Product Development of this enhancement request.

**Comment by INeedCaffeine** [comment] 2022-01-05 16:35
I am unable to reproduce this using the 12.0.1 Notes client and mail template.  I tried the following steps with GTM, Sametime & WebEx:

1: Create a non-repeating meeting with User A which included a room from R&R and an online meeting
2: User A opened the invite and clicked on Accept

In all cases the invitee was able to Accept the meeting (it gets put on their Calendar) and the Chair gets an Accept notice back.

@jmcxw : Are you or your customer using the 12.0.1 Notes client & mail template when the invitee sees the problem?

**Comment by spanky762** [comment] 2022-06-28 13:26
Unable to reproduce, closing issue.

**Closed by spanky762** 2022-06-28 13:26 UTC
Labels: enhancement
