### ISSUE TITLE
[BUG] oauth Token expires after short period of time

### ISSUE THREAD

**Issue by tkheuer** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#121] opened 2021-10-14 12:22 UTC
**HCL Product Version**
Notes 11.01 FP3

**Describe the bug**
OauthToken expires after short period of time

**Error Message**
Error message in Notes client: Please check notes log for details. 

Error message in console.log: {"error":{"code":"InvalidAuthenticationToken","message":"Access token has expired or is not yet valid.","innerError":{"date":"2021-10-12T08:13:54","request-id":"677b1724-8699-444e-ae39-447362d335f3","client-request-id":"677b1724-8699-444e-ae39-447362

(console.log is attached)

**To Reproduce**
1. Schedule new Teams Onlinmeeting
2. See error

**Expected behavior**
The token should refresh itselfs. 
In an other it environment in our company (other firewall/networksettings) we don't have this kind of issue.
Only if the users goes into the meeting credentials and validate the authtoken manually, it works again for a short period of time. 

**Screenshots**
Screenshot is  attached

**Desktop (please complete the following information):**
Windows 10

**Additional context**

Why the token never updates automatically in this environment? 
Are there  any special settings or things I can check regarding the automatically update of the oauth token?
[console.log](https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/files/7345920/console.log)
![pic27578](https://user-images.githubusercontent.com/92520525/137316299-6a103c7b-bd7c-45cb-b02e-29957b330c65.gif)

**Comment by tkheuer** [comment] 2021-10-21 16:05
Here are a new console.log and the corresponding log.nsf.txt file.
[console.log](https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/files/7391261/console.log)
[log.nsf.txt](https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/files/7391262/log.nsf.txt)

**Comment by spanky762** [comment] 2021-10-21 16:40
Hi @tkheuer 

Thanks for posting these logs.  I will go through them and try to reproduce on my end, and will get back to you as soon as I can.

**Comment by tkheuer** [comment] 2021-11-02 14:39
Hi @spanky762 
Are there any new regarding my reported issue?

**Comment by tkheuer** [comment] 2021-11-17 15:28
Meantime I have also tested it with a Notes 12 Beta 2 Client and Notes 12 mailtemplate. 
Here I have the same problem if a proxy server with windows environment variables (HTTPS_PROXY "http://xxx.xxx.xxx.xxx:8080/")  are used.

**Comment by INeedCaffeine** [comment] 2022-01-19 16:47
@tkheuer : Do you see the problem in the 12.0.1 client & template?

**Comment by tkheuer** [comment] 2022-01-20 14:06
yes, same problem in 12.0.1 client with 12.0.1 template.
My workaround in the script code is described here: 
#123

**Comment by spanky762** [comment] 2022-06-28 13:15
I suspect that the flag for hasAuthError is not getting properly set in your environment due to the way your firewall is handling the traffic; however your workaround for refreshing the token every time is working (and does not seem to pose a problem).  I will look into the code and see if I can reproduce / validate my suspicions (and if validated pass them on to production).    Closing this issue now.

**Closed by spanky762** 2022-06-28 13:15 UTC
Labels: bug
