### ISSUE TITLE
[BUG] If Schedule Online Meeting selected after meeting creation invitees don't get the Teams link

### ISSUE THREAD

**Issue by KSchroeder2021** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#110] opened 2021-08-31 15:42 UTC
Steps to reproduce:
Chair creates a meeting invitation. The invitee confirms the invitation. After that, the chair changes the meeting and creates a Teams link using schedule online meeting.
a) nothing else is changed. Then the invitees don't get any notification about this and they don't get the Teams link.
b) the meeting is moved to another date/time. Then the invitees get the "newly planned' invitation and the Teams link is shown there. But the Teams link will never be shown in the calendar entry of the invitee.

Any changes including the "Schedule Online Meeting" changes should be transparent for all invitees and should be properly shown in the corresponding calendars.

**Comment by spanky762** [comment] 2021-09-01 16:07
Duplicate of issue #109 

When a user clicks the Save and Send Invitations button on a calendar entry, the code to actually send invitations (or updates to previously sent invitations) only runs if certain **_trigger_** fields have changed value.  These fields are subject, invitee(s), start date & time, end date & time, etc.  On a new calendar entry document these fields will change from blank to whatever new value is entered, so the invitations are sent.   

On an _existing_ calendar entry, things get a little strange.  If you update an existing calendar entry document, but don't change values for any of the trigger fields, then update notifications will NOT be sent, _even if you click the "Save and Send Invitations" button._  

The DOMI code does NOT update any of these trigger fields when you create, update, or delete an online meeting.  The meeting location and meeting id fields are updated, but they are not trigger fields.   

There are no plans to modify the Open Source DOMI code, as any such modification will cause DOMI to modify calendar information.  

A workaround for this can be performed as a user training issue -which is to change the Subject of the calendar document (any non-whitespace change will work) whenever an online meeting is created, updated, or deleted.  

I will refer this issue (and my response) to the Core Notes Development team so they are aware of it.

**Closed by spanky762** 2021-09-01 16:07 UTC
Labels: bug

**Comment by spanky762** [comment] 2021-09-01 18:00
I spoke with Bruce Kahn, this is fixed for 12.0.1
