### ISSUE TITLE
[BUG] Notes crashes after pushing Get Sametime Token

### ISSUE THREAD

**Issue by FranklinIndigo** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#42] opened 2021-06-11 11:51 UTC
**HCL Product Version**
Notes Client 11.0.1FP3 with mail template Notes 11.0.1 (Dutch language)

**Describe the bug**
Notes 11FP3 crashes after pushing Get Sametime Token.

**Error Message**
no error, only a crash

**To Reproduce**
1. download and sign the Domi.nsf
2. edit the library domiConstantsBE and put our Sametime meeting server URL in it
3. install in our mail template 11.0.1 (Dutch version) with the button "install DOMI"
4. Replace template on my mailfile
5. In the mailfile: Create / Online Meeting Credentials
6. Select Sametime as the service
7. Push button "Get Sametime Token" >> Notes Client crash
(I tried this several times and I did the installation twice with a clean temaple to be sure)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by paulswithers** [comment] 2021-06-11 12:03
If the self-signed certificate is the cause, can you post the steps you had to take? I'll update the documentation.

**Comment by FranklinIndigo** [comment] 2021-06-11 12:20
We don't use self-signed certificates. We use a wildcard certificate from RapidSSL and we put it on the meeting and proxy server.

**Comment by paulswithers** [comment] 2021-06-11 12:40
Could you add the notes.ini variable, `Debug_NotesHTTPRequest=1` and see if there's anything unusual in the console.log in <notes>\IBM_TECHNICAL_SUPPORT? That notes.ini variable provides debugging information for the underlying curl calls from Notes Clieny. Please be aware this doesn't mask any sensitive data, so I would not recommend sharing the logs in full.

**Comment by spanky762** [comment] 2021-06-13 16:31
I am out of the office until 06/15/2021.

I will return to the office on Tuesday, June 14.

I will attempt to check my email and respond daily; however internet access
will be extremely limited. I should have cellular telephone service
available.

If this is an emergency please call me at +1 616-295-1683

-Devin.



Note: This is an automated response to your message  "Re:
[HCL-TECH-SOFTWARE/domino-online-meeting-integration] [BUG] Notes crashes
after pushing Get Sametime Token (#42)" sent on 06/11/2021 8:03:34 AM.

This is the only notification you will receive while this person is away.

**Comment by spanky762** [comment] 2021-06-13 16:31
I am out of the office until 06/15/2021.

I will return to the office on Tuesday, June 14.

I will attempt to check my email and respond daily; however internet access
will be extremely limited. I should have cellular telephone service
available.

If this is an emergency please call me at +1 616-295-1683

-Devin.



Note: This is an automated response to your message  "Re:
[HCL-TECH-SOFTWARE/domino-online-meeting-integration] [BUG] Notes crashes
after pushing Get Sametime Token (#42)" sent on 06/11/2021 8:02:02 AM.

This is the only notification you will receive while this person is away.

**Comment by spanky762** [comment] 2021-06-13 16:31
I am out of the office until 06/15/2021.

I will return to the office on Tuesday, June 14.

I will attempt to check my email and respond daily; however internet access
will be extremely limited. I should have cellular telephone service
available.

If this is an emergency please call me at +1 616-295-1683

-Devin.



Note: This is an automated response to your message  "Re:
[HCL-TECH-SOFTWARE/domino-online-meeting-integration] [BUG] Notes crashes
after pushing Get Sametime Token (#42)" sent on 06/11/2021 8:40:53 AM.

This is the only notification you will receive while this person is away.

**Comment by spanky762** [comment] 2021-06-13 16:31
I am out of the office until 06/15/2021.

I will return to the office on Tuesday, June 14.

I will attempt to check my email and respond daily; however internet access
will be extremely limited. I should have cellular telephone service
available.

If this is an emergency please call me at +1 616-295-1683

-Devin.



Note: This is an automated response to your message
"[HCL-TECH-SOFTWARE/domino-online-meeting-integration] [BUG] Notes crashes
after pushing Get Sametime Token (#42)" sent on 06/11/2021 7:52:09 AM.

This is the only notification you will receive while this person is away.

**Comment by spanky762** [comment] 2021-06-13 16:31
I am out of the office until 06/15/2021.

I will return to the office on Tuesday, June 14.

I will attempt to check my email and respond daily; however internet access
will be extremely limited. I should have cellular telephone service
available.

If this is an emergency please call me at +1 616-295-1683

-Devin.



Note: This is an automated response to your message  "Re:
[HCL-TECH-SOFTWARE/domino-online-meeting-integration] [BUG] Notes crashes
after pushing Get Sametime Token (#42)" sent on 06/11/2021 8:21:05 AM.

This is the only notification you will receive while this person is away.

**Comment by patrickschneider** [comment] 2021-06-16 08:22
Hello,
we're encountering the same problem, it's independent of the Mail Template Language (tried 1101 German and 1200 English) on Notes 12.0.
Notes Crashes as soon as we click on "Get Sametime Token"

Sametime Meetings 11.5 using a SSL-Certificate from Lets Encrypt.

I added Debug_NotesHTTPRequest=1

[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]    Trying AA.BB.CC.DD:443...
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  Connected to meetings.company.com (AA.BB.CC.DD) port 443 (#0)
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  ALPN, offering http/1.1
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  successfully set certificate verify locations:
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]   CAfile: c:\HCL\Notes\Data\cacert.pem
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]   CApath: none
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Request SSL data:  
[1AB4:0002-1AB8]  
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  TLSv1.3 (OUT), TLS handshake, Client hello (1):
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Request SSL data:  
[1AB4:0002-1AB8]  ¨
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Response SSL data:  
[1AB4:0002-1AB8]   
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  TLSv1.3 (IN), TLS handshake, Server hello (2):
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Response SSL data:  
[1AB4:0002-1AB8]  
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Response SSL data:  
[1AB4:0002-1AB8]   
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  TLSv1.2 (IN), TLS handshake, Certificate (11):
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Response SSL data:  
[1AB4:0002-1AB8]  
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Request SSL data:  
[1AB4:0002-1AB8]   
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  TLSv1.2 (OUT), TLS alert, unknown CA (560):
[1AB4:0002-1AB8] LSXBE HTTP debug information type: HTTP Request SSL data:  
[1AB4:0002-1AB8]   
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  SSL certificate problem: unable to get local issuer certificate
[1AB4:0002-1AB8] LSXBE HTTP debug information type: Generic Information:  
[1AB4:0002-1AB8]  Closing connection 0

It looks like the Lets Encrypt CA (and RapidSSL CA) is not in the List of trusted CAs for LotusScript?

How can we add the CA to the List of trusted CAs?

Best Regards,
Patrick Schneider

**Comment by FranklinIndigo** [comment] 2021-06-16 08:23
Hi Paul, I added the debug setting in the notes.ini and tried it again. One line in the console.log seems related to SSL:

SSL certificate problem: unable to get local issuer certificate

kind regards,
Franklin

**Comment by patrickschneider** [comment] 2021-06-16 08:54
Hello,

is https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0069539 the right way to add the CA to the list of trusted CAs? The cacert File should be the one in the Notes Client's Data Directory, right?
Best regards,
Patrick

**Comment by patrickschneider** [comment] 2021-06-16 09:28
Hi again,

adding the Root and Intermediate CA Certificates (base64 encoded X.509) in the cacert.pem (Notes-Data Directory in the Single-User Client) fixed the Problem.
For Multi-User Clients (with Shared-Data Directory), the cacert.pem is located in the Folder defined in the NotesSharedData Notes.ini Entry (e.g. C:\ProgramData\HCL\Notes\Data\Shared\ - unfortunately, it looks like the file is not used and even if you copy the file to the Users Notes Data Directory, the crash still occurs).
See also https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0084642
But I managed to fix this by putting a copy of the cacert.pem to the NotesSharedData Subdirectory MUI\DE  ( C:\ProgramData\HCL\Notes\Data\Shared\mui\de )

Hope this helps,
Patrick

**Comment by spanky762** [comment] 2021-06-25 14:44
@patrickschneider  thank you for your input and diagnosis efforts on this.  We are currently trying to figure out what should be the right way to resolve this should be.  I'm leaving this issue open for the time being, but we are not ignoring it.

**Comment by paulswithers** [comment] 2021-06-25 15:05
I've updated the Troubleshooting page of the documentation, hopefully to resolve it https://opensource.hcltechsw.com/domino-online-meeting-integration/troubleshooting/#notes-crashes-after-get-sametime-token. I'm not sure what the best practice solution is for ensuring certificates are available from Sametime for other systems making HTTP requests though.

**Comment by spanky762** [comment] 2021-07-08 14:33
Documentation updated for troubleshooting this issue.  Closing

**Closed by spanky762** 2021-07-08 14:33 UTC
Labels: bug
