### ISSUE TITLE
Updated "_Calendar Entry" form did not get signed - resulting in ECL alerts

### ISSUE THREAD

**Issue by slapraik-intec** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#43] opened 2021-06-11 17:50 UTC
Hi.

Product version used: Notes 12.0.0 GA

Steps I carried out:

1. Created a copy of the mail12 template (mail12-domi.ntf)
2. Signed the DOMI application
3. Ran the "Install DOMI" action and updated the mail12-domi.ntf template
4. Upgraded a mailfile using the new template
5. Opened the mailfile
6. When creating a new meeting, I get several ECL alerts indicating "no signer"
7. Checked the mailfile design and found the "_Calendar Entry" form has no $Signature field
8. Checked the custom mail12 template and the "_Calendar Entry" form has no $Signature field

I deleted the custom template and tried the whole process again just in case, but got the same result.

Regards.
Simon

**Comment by spanky762** [comment] 2021-06-13 16:31
I am out of the office until 06/15/2021.

I will return to the office on Tuesday, June 14.

I will attempt to check my email and respond daily; however internet access
will be extremely limited. I should have cellular telephone service
available.

If this is an emergency please call me at +1 616-295-1683

-Devin.



Note: This is an automated response to your message
"[HCL-TECH-SOFTWARE/domino-online-meeting-integration] Updated "_Calendar
Entry" form did not get signed - resulting in ECL alerts (#43)" sent on
06/11/2021 1:50:48 PM.

This is the only notification you will receive while this person is away.

**Comment by paulswithers** [comment] 2021-06-14 08:48
Can you confirm OS run on and whether the signature of the "_Calendar Entry" prior to installing DOMI was the same as the signer running the installation. I have seen that symptom, but can't reproduce it. 

The code doing the replacement is [this chunk of LotusScript](https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/blob/main/notes/Code/Agents/01.%20Install%20DOMI%20in%20Target%20Mail%20Db.lsa#L163). As you can see it's just streaming the existing DXL, inserting a reference to our subform at the end of the form, and streaming it back in. It looks like the signature is the `<wassignedby>` element in the DXL. 

If the same ID that signed the Form imports it in, the signature is honoured. I suspect the DXL round-tripping removes that if the ID that last signed the Form and the ID performing the import is different. If that's the case, I can update the documentation accordingly.

**Comment by spanky762** [comment] 2021-06-14 14:01
I am out of the office until 06/15/2021.

I will return to the office on Tuesday, June 14.

I will attempt to check my email and respond daily; however internet access
will be extremely limited. I should have cellular telephone service
available.

If this is an emergency please call me at +1 616-295-1683

-Devin.



Note: This is an automated response to your message  "Re:
[HCL-TECH-SOFTWARE/domino-online-meeting-integration] Updated "_Calendar
Entry" form did not get signed - resulting in ECL alerts (#43)" sent on
06/14/2021 4:48:56 AM.

This is the only notification you will receive while this person is away.

**Comment by spanky762** [comment] 2021-07-13 12:19
Closed by PR #80

**Closed by spanky762** 2021-07-13 12:19 UTC
